const MAP: Record<string, { label: string; bg: string; fg: string }> = {
  active: { label: 'نشط', bg: '#e9f3ec', fg: '#2e7d4f' },
  upcoming: { label: 'قادمة', bg: '#eaf0f8', fg: '#1c4b8f' },
  completed: { label: 'مكتملة', bg: '#e9f3ec', fg: '#2e7d4f' },
  done: { label: 'مكتملة', bg: '#f0eef4', fg: '#5c4a7a' },
  cancelled: { label: 'ملغى', bg: '#f8ecec', fg: '#a34b4b' },
  scheduled: { label: 'مجدولة', bg: '#eaf0f8', fg: '#1c4b8f' },
  inactive: { label: 'غير نشط', bg: '#f4f1ea', fg: '#8a8478' },
  closed: { label: 'متوقفة', bg: '#f4f1ea', fg: '#8a8478' },
  graduated: { label: 'متخرج', bg: '#eaf0f8', fg: '#1c4b8f' },
  confirmed: { label: 'مؤكد', bg: '#e9f3ec', fg: '#2e7d4f' },
  pending: { label: 'معلّقة', bg: '#f7f0e1', fg: '#8a6a20' },
  paid: { label: 'مسدَّدة', bg: '#e9f3ec', fg: '#2e7d4f' },
  overdue: { label: 'متأخرة', bg: '#f8ecec', fg: '#a34b4b' },
  refunded: { label: 'مسترجعة', bg: '#eaf0f8', fg: '#1c4b8f' },
  pending_payment: { label: 'بانتظار الدفع', bg: '#eaf0f8', fg: '#1c4b8f' },
  pending_coordination: { label: 'بانتظار تنسيق', bg: '#fff3e6', fg: '#c47a1a' },
  suspended: { label: 'موقوف', bg: '#f4f1ea', fg: '#8a8478' },
  expired: { label: 'منتهي', bg: '#f4f1ea', fg: '#8a8478' },
  frozen: { label: 'مجمَّد', bg: '#eaf0f8', fg: '#1c4b8f' },
  notice: { label: 'تنبيه', bg: '#f7f0e1', fg: '#c47a1a' },
  follow_up: { label: 'متابعة', bg: '#f8ecec', fg: '#a34b4b' },
  excellent: { label: 'ممتاز', bg: '#e9f3ec', fg: '#2e7d4f' },
  good: { label: 'جيد', bg: '#eaf0f8', fg: '#1c4b8f' },
  needs_follow_up: { label: 'يحتاج متابعة', bg: '#f7f0e1', fg: '#c47a1a' },
  general: { label: 'عام', bg: '#eaf0f8', fg: '#1c4b8f' },
  targeted: { label: 'خاص', bg: '#f0eef4', fg: '#5c4a7a' },
  ended: { label: 'منتهٍ', bg: '#f4f1ea', fg: '#8a8478' },
  draft: { label: 'مسودة', bg: '#f7f0e1', fg: '#c47a1a' },
  finalized: { label: 'مقفلة', bg: '#e9f3ec', fg: '#2e7d4f' },
  fixed_monthly: { label: 'راتب ثابت', bg: '#eaf0f8', fg: '#1c4b8f' },
  per_session: { label: 'بالحصة', bg: '#f0eef4', fg: '#5c4a7a' },
  manual: { label: 'يدوي', bg: '#f7f0e1', fg: '#8a6a20' },
  composite: { label: 'مركّب', bg: '#eaf0f8', fg: '#1c4b8f' },
  base_salary: { label: 'راتب أساسي', bg: '#eaf0f8', fg: '#1c4b8f' },
  per_session_rate: { label: 'سعر حصة', bg: '#f0eef4', fg: '#5c4a7a' },
  fixed_incentive: { label: 'حافز ثابت', bg: '#f7f0e1', fg: '#8a6a20' },
  recurring_bonus: { label: 'مكافأة متكررة', bg: '#e9f3ec', fg: '#2e7d4f' },
  present: { label: 'حاضر', bg: '#e9f3ec', fg: '#2e7d4f' },
  absent: { label: 'غائب', bg: '#f8ecec', fg: '#a34b4b' },
  late: { label: 'متأخر', bg: '#f7f0e1', fg: '#c47a1a' },
  half_day: { label: 'نصف يوم', bg: '#eaf0f8', fg: '#1c4b8f' },
  on_leave: { label: 'إجازة', bg: '#f0eef4', fg: '#5c4a7a' },
  approved: { label: 'موافق عليه', bg: '#e9f3ec', fg: '#2e7d4f' },
  rejected: { label: 'مرفوض', bg: '#f8ecec', fg: '#a34b4b' },
  full_time: { label: 'دوام كامل', bg: '#eaf0f8', fg: '#1c4b8f' },
  part_time: { label: 'دوام جزئي', bg: '#f0eef4', fg: '#5c4a7a' },
  contractor: { label: 'متعاقد', bg: '#f7f0e1', fg: '#8a6a20' },
  delivery: { label: 'توصيل', bg: '#eaf0f8', fg: '#1c4b8f' },
  pickup: { label: 'استلام', bg: '#f0eef4', fg: '#5c4a7a' },
  processing: { label: 'قيد التجهيز', bg: '#eaf0f8', fg: '#1c4b8f' },
  ready_for_pickup: { label: 'جاهز للاستلام', bg: '#f0eef4', fg: '#5c4a7a' },
  out_for_delivery: { label: 'بالطريق', bg: '#f0eef4', fg: '#5c4a7a' },
  delivered: { label: 'تم التسليم', bg: '#e9f3ec', fg: '#2e7d4f' },
  new: { label: 'جديد', bg: '#eaf0f8', fg: '#1c4b8f' },
  accepted: { label: 'تم القبول', bg: '#e9f3ec', fg: '#2e7d4f' },
  in_progress: { label: 'قيد المعالجة', bg: '#fff3e6', fg: '#c47a1a' },
  replied: { label: 'تم الرد', bg: '#f0eef4', fg: '#5c4a7a' },
  in_app: { label: 'داخل النظام', bg: '#eaf0f8', fg: '#1c4b8f' },
  email: { label: 'إيميل', bg: '#e9f3ec', fg: '#2e7d4f' },
  whatsapp: { label: 'واتساب', bg: '#e9f3ec', fg: '#2e7d4f' },
  invoice_mark_paid: { label: 'تأكيد دفع فاتورة', bg: '#e9f3ec', fg: '#2e7d4f' },
  invoice_refund: { label: 'استرداد فاتورة', bg: '#eaf0f8', fg: '#1c4b8f' },
  subscription_changed: { label: 'تغيير اشتراك', bg: '#f0eef4', fg: '#5c4a7a' },
  role_permissions_updated: { label: 'تحديث صلاحيات دور', bg: '#f7f0e1', fg: '#c47a1a' },
  role_deleted: { label: 'حذف دور', bg: '#f8ecec', fg: '#a34b4b' },
  subscription_frozen: { label: 'تجميد اشتراك', bg: '#eaf0f8', fg: '#1c4b8f' },
  subscription_unfrozen: { label: 'إنهاء تجميد', bg: '#e9f3ec', fg: '#2e7d4f' },
  schedule_conflict_overridden: { label: 'تجاوز تعارض جدول', bg: '#fff3e6', fg: '#c47a1a' },
  student_transferred_group: { label: 'نقل طالب بين شعب', bg: '#eaf0f8', fg: '#1c4b8f' },
  closed_ticket: { label: 'مغلق', bg: '#f4f1ea', fg: '#8a8478' },
};

export function StatusBadge({ status }: { status: string }) {
  const key = status.replaceAll('.', '_');
  const s = MAP[status] ?? MAP[key] ?? { label: status, bg: '#f4f1ea', fg: '#8a8478' };
  return (
    <span
      className="inline-block whitespace-nowrap rounded-full px-2.5 py-1 text-[11.5px] font-bold"
      style={{ background: s.bg, color: s.fg }}
    >
      {s.label}
    </span>
  );
}
