import { announcements } from '@/data/announcements';
import { faqs, benefits, parentGets, heroFeatures, navItems, tabItems, studioCats, studioItems, contact } from '@/data/content';
export type MarketingMap = Record<string, Record<string, unknown>>;

export const MARKETING_FALLBACKS: MarketingMap = {
  hero: {
    badge_text: 'تعليم حضوري في الكويت',
    title_line1: 'مستقبل ابنك',
    title_line2: 'يبدأ بخطوة',
    description: 'تعليم حضوري ومتابعة مستمرة تساعد أبناءك على الفهم، الإنجاز، والاستعداد للاختبارات.',
    cta_primary_text: 'سجّل ابنك الآن',
    cta_primary_link: 'register',
    cta_secondary_text: 'استكشف البرامج',
    cta_secondary_link: 'programs',
    trust: ['معلمون متخصصون', 'متابعة مستمرة', 'برامج حضورية', 'تسجيل ودفع إلكتروني'],
    floating: [
      { icon: 'fa-solid fa-users', label: 'معلمون\nمتخصصون' },
      { icon: 'fa-solid fa-chart-line', label: 'متابعة\nمستمرة' },
      { icon: 'fa-solid fa-book-open', label: 'حل الواجبات\nومراجعة الاختبارات' },
    ],
    heroFeatures,
    background_image: null,
    background_placeholder: 'صورة طلاب في بيئة تعليمية (4:3) — /public/hero-students.jpg',
    symbol_logo: '/assets/talal-symbol-light.png',
  },
  announcements: {
    items: announcements.map((a) => ({
      id: a.id,
      icon: a.icon,
      title: a.title,
      desc: a.desc,
      cta_text: a.cta,
      target_view: a.view,
      bg_gradient: a.bg,
    })),
  },
  nav: {
    institute_name_ar: 'طلال أكاديمي',
    institute_name_en: 'TALAL ACADEMY',
    header_cta_primary: 'سجّل ابنك الآن',
    header_cta_secondary: 'دخول ولي الأمر',
    footer_paragraph: 'تعليم حضوري. متابعة مستمرة. نتائج أفضل.',
    footer_links_title: 'روابط',
    footer_contact_title: 'تواصل',
    footer_hours_title: 'الدوام',
    footer_management_prefix: 'إدارة:',
    footer_copyright: 'Talal Academy',
    nav_items: navItems.map((n) => ({ view_id: n.id, label: n.label, icon: n.icon })),
    tab_items: tabItems.map((n) => ({ view_id: n.id, label: n.label, icon: n.icon })),
    footer_legal_links: [
      { label: 'الشروط والأحكام', url: '#' },
      { label: 'سياسة الخصوصية', url: '#' },
      { label: 'سياسة الاسترجاع', url: '#' },
    ],
    social_links: [
      { platform: 'whatsapp', url: '' },
      { platform: 'instagram', url: '' },
      { platform: 'snapchat', url: '' },
      { platform: 'x-twitter', url: '' },
    ],
  },
  programs: {
    section_eyebrow: 'PROGRAMS',
    section_title: 'المراحل الدراسية',
    section_sub: 'اختر المرحلة ثم استكشف الصفوف والباقات والميزات.',
    explore_cta: 'استكشف الباقات والميزات',
    grades_cta: 'عرض الصف',
    program_cta: 'سجّل الآن',
    vip_cta: 'طلب حصة VIP',
    currency: 'د.ك',
    package_label: 'الباقة الشاملة',
    single_subjects_label: 'المواد المفردة',
    features_title: 'المميزات',
    packages_title: 'الباقات والأسعار',
    back_label: 'رجوع',
    grades_heading: 'اختر الصف لاستعراض الميزات والباقات',
    grade_heading: 'الميزات والباقات وأسعار المواد',
    loading_label: 'جارٍ تحميل البرامج…',
    error_label: 'تعذّر تحميل البرامج',
    empty_grades: 'لا توجد صفوف في هذه المرحلة حالياً.',
    empty_package: 'لا توجد باقة شاملة لهذا الصف حالياً.',
    empty_subjects: 'لا توجد أسعار مواد مفردة لهذا الصف حالياً.',
    features: parentGets,
    stage_cards: [
      { stage_id: 2, image: null, badge: null, short_desc: 'الصف الأول — الخامس' },
      { stage_id: 1, image: null, badge: null, short_desc: 'الصف السادس — التاسع' },
      { stage_id: 3, image: null, badge: null, short_desc: 'الصفوف الثانوية' },
    ],
  },
  about: {
    eyebrow: 'ABOUT',
    title: 'عن طلال أكاديمي',
    sub: 'بيئة تعليمية صُممت ليشعر الطالب بالراحة ويستفيد فعليًا.',
    why_us_title: 'لماذا طلال أكاديمي؟',
    info_section_title: 'الدوام والإدارة',
    studio_title: 'استديو المعهد',
    studio_section_sub: 'صور من فصولنا ومرافقنا وفعالياتنا',
    days_label: 'أيام الدوام',
    hours_label: 'وقت الدوام',
    management_label: 'الإدارة',
    days_note: '— 5 أيام أسبوعيًا',
    benefits,
    studio_cats: studioCats,
    studio_items: studioItems,
  },
  faq: {
    page_eyebrow: 'FAQ',
    page_title: 'الأسئلة الشائعة',
    faqs,
  },
  contact: {
    page_eyebrow: 'CONTACT',
    page_title: 'تواصل معنا',
    page_description: 'اترك بياناتك وسنتواصل معك لتحديد البرنامج المناسب لابنك، أو اتصل بنا مباشرة.',
    phones: contact.phones,
    management: contact.management,
    days: contact.days,
    hours: contact.hours,
    country: contact.country,
    form_labels: {
      name: 'الاسم',
      phone: 'رقم الواتساب',
      phone_secondary: 'رقم تواصل ثاني (اختياري)',
      stage: 'المرحلة',
      message: 'رسالتك',
      submit: 'إرسال',
      submitting: 'جارٍ الإرسال…',
      stage_placeholder: 'اختر المرحلة',
      name_placeholder: 'مثال: عبدالله الأحمد',
      phone_placeholder: '+965 XXXX XXXX',
      message_placeholder: 'اكتب استفسارك…',
    },
    success_title: 'تم إرسال رسالتك',
    success_message: 'سنتواصل معك في أقرب وقت.',
    success_cta: 'إرسال رسالة أخرى',
  },
  'private-lessons': {
    section_eyebrow: 'PRIVATE LESSONS',
    section_title: 'الحصص الخاصة',
    section_sub: 'عبّئ بيانات الطالب والمادة وعدد الساعات — سنتواصل معك لتنسيق الحصة، بدون تسجيل.',
    form_title: 'طلب حصة خاصة',
    submit_label: 'إرسال الطلب',
    submitting_label: 'جارٍ الإرسال…',
    success_title: 'تم استلام طلبك',
    success_message: 'سيتواصل معك فريق المعهد قريبًا لتنسيق الحصة الخاصة.',
    success_cta: 'إرسال طلب آخر',
    student_name_label: 'اسم الطالب',
    phone_label: 'رقم التواصل',
    phone_secondary_label: 'رقم تواصل ثاني',
    grade_label: 'الصف',
    subject_label: 'المادة',
    hours_label: 'عدد الساعات المطلوبة',
    grade_placeholder: 'اختر الصف',
    subject_placeholder: 'اختر المادة',
    hours_placeholder: 'اختر عدد الساعات',
    default_features: [
      { icon: 'fa-solid fa-user-tie', title: 'معلم متخصص', desc: '' },
      { icon: 'fa-solid fa-clock', title: 'موعد مرن', desc: '' },
      { icon: 'fa-solid fa-bullseye', title: 'تركيز على نقاط ضعف الطالب', desc: '' },
      { icon: 'fa-solid fa-crown', title: 'تجربة VIP', desc: '' },
    ],
  },
  registration: {
    guide_name: 'سارة',
    guide_role: 'مرشدة التسجيل',
    aside_image: null,
    mascot_lines: [
      'أهلاً! أنا سارة. لنبدأ — أي مرحلة دراسية يدرس فيها ابنك؟',
      'جميل. الآن حدّد صفه بالتحديد.',
      'ممتاز! اختر الباقة المناسبة لابنك — السعر يظهر فورًا.',
      'نحتاج التحقق من رقمك لنبقيك على اطّلاع بتقدّم ابنك.',
      'بيانات الطالب تساعد المعلمين على متابعته من اليوم الأول.',
      'اختر طريقة الدفع الأنسب لك — كامل، تقسيط، أو في المعهد.',
      'تم! أهلاً بابنك في طلال أكاديمي. سنتواصل معك قريبًا.',
    ],
    step_labels: [
      'اختر المرحلة',
      'اختر الصف',
      'اختر الباقة',
      'بيانات ولي الأمر',
      'بيانات الطالب',
      'الدفع',
      'تم التسجيل',
    ],
  },
};

export function useSection<T extends Record<string, unknown>>(map: MarketingMap, key: string): T {
  const live = map[key];
  const fallback = MARKETING_FALLBACKS[key] ?? {};
  return { ...fallback, ...(live ?? {}) } as T;
}
